# ============================================
# HAProxy Configuration
# Load Balancer on VIP
# ============================================

frontend myapp
    bind *:5000
    default_backend servers

backend servers
    balance roundrobin
    server vm1 192.168.142.144:80 check
    server vm2 192.168.142.145:80 check